version: 1.1.0

debug: false

port: 705

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles:
      - /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/db-server-cert.pem
    client:
      certfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/db-client-cert.pem
      keyfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/db-client-key.pem

ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<portbase>
  tls:
    certfiles:
      - /path/to/ldap-cert.pem
    client:
      certfile: /path/to/client-cert.pem
      keyfile: /path/to/client-key.pem
  attribute:
    names: ['uid', 'member']

affiliations:
  org1:
    - department1
    - department2
  org2:
    - department1

ca:
  name: ca
  keyfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/ca-key.pem
  certfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/ca-cert.pem
  chainfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/ca-chain.pem

tls:
  enabled: true
  certfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/tls-cert.pem
  keyfile: /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/tls-key.pem
  clientauth:
    type: noclientcert
    certfiles:
      - /Users/newowner/Desktop/meds-Scan-backend/fabric-ca-server/client-cert.pem

csr:
  cn: fabric-ca-server
  names:
    - C: US
      ST: North Carolina
      L: Raleigh
      O: Hyperledger
      OU: Fabric
  hosts:
    - localhost
  ca:
    pathlen: 0
    pathlenzero: true
    expiry: 131400h

bccsp:
  default: SW
  sw:
    Hash: SHA2
    Security: 256
    FileKeyStore:
      KeyStore: msp/keystore

intermediate:
  parentserver:
    url: http://<username>:<password>@<address>:<port>
    caname: ca
  enrollment:
    hosts:
      - localhost
    profile: ca
    label: fabric-ca-server
  tls:
    certfiles:
      - /Users/newowner/Desktop/meds-Scan-backend/certs/intermediate-cert.pem
    client:
      certfile: /Users/newowner/Desktop/meds-Scan-backend/certs/intermediate-client-cert.pem
      keyfile: /Users/newowner/Desktop/meds-Scan-backend/certs/intermediate-client-key.pem

metrics:
  provider: prometheus
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 10s
    prefix: server
